blank_issues_enabled: true
contact_links:
  - name: ":construction_worker: General Community Support"
    url: https://discord.pivx.org
    about: Please ask general support questions in our discord server.
